<?php

/**
 * @file
 * Contains license.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function license_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the license module.
    case 'help.page.license':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides license entity type, which may be used to control user access to other entities.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function license_theme() {
  $theme = [];
  $theme['license_entity'] = array(
    'render element' => 'elements',
    'file' => 'license_entity.page.inc',
    'template' => 'license_entity',
  );
  $theme['license_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'license_entity.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function license_theme_suggestions_license_entity(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#license_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'license_entity__' . $sanitized_view_mode;
  $suggestions[] = 'license_entity__' . $entity->bundle();
  $suggestions[] = 'license_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'license_entity__' . $entity->id();
  $suggestions[] = 'license_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
