<?php

/**
 * @file
 * Contains license.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Access\AccessResult;

// License statuses.
define('LICENSE_CREATED', 0);
define('LICENSE_PENDING', 1);
define('LICENSE_ACTIVE', 2);
define('LICENSE_EXPIRED', 3);
define('LICENSE_SUSPENDED', 5);
define('LICENSE_REVOKED', 4);

/**
 * Implements hook_help().
 */
function license_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the license module.
    case 'help.page.license':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides license type, which may be used to control user access to other entities.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function license_theme() {
  $theme = [];
  $theme['license'] = array(
    'render element' => 'elements',
    'file' => 'license.page.inc',
    'template' => 'license',
  );
  $theme['license_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'license.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function license_theme_suggestions_license(array $variables) {
  $suggestions = array();
  $entity = $variables['elements']['#license'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'license__' . $sanitized_view_mode;
  $suggestions[] = 'license__' . $entity->bundle();
  $suggestions[] = 'license__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'license__' . $entity->id();
  $suggestions[] = 'license__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_access();
 */
function license_entity_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {
  switch ($operation) {
    case 'view':

      $control_access = FALSE;
      $license_types = \Drupal::entityTypeManager()->getStorage('license_type')->loadMultiple();
      foreach ($license_types as $license_type) {
        $target_entity_type = $license_type->get('target_entity_type');
        if ($entity->getEntityTypeId() == $target_entity_type
          && (empty($license_type->get('roles')) || array_intersect($account->getRoles(), $license_type->get('roles')))) {
          $control_access = TRUE;
          break;
        }
      }

      if ($control_access) {
        $licenses = \Drupal::entityTypeManager()
          ->getStorage('license')
          ->loadByProperties([
            'user_id' => $account->id(),
            'licensed_entity' => $entity->id(),
          ]);
        /** @var \Drupal\Core\Entity\EntityInterface $license */
        foreach ($licenses as $license) {
          if ($license->isActive()) {
            $access = AccessResult::allowed();
            $access->addCacheTags($license->getCacheTags());

            return $access;
          }
        }

        $access = AccessResult::forbidden();
        $access->addCacheTags($license->getCacheTags());
        return $access;
      }
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_cron().
 */
function license_cron() {
  $query = \Drupal::entityQuery('license');
  $query->condition('status', LICENSE_EXPIRED, '!=')
    ->condition('expires_automatically', '1')
    ->condition('expiry', REQUEST_TIME, '<=');
  if ($ids = $query->execute()) {
    $licenses = \Drupal\license\Entity\License::loadMultiple($ids);

    // @todo Queue this!
    /** @var \Drupal\Core\Entity\EntityInterface $license */
    foreach ($licenses as $license) {
      $license->set('status', LICENSE_EXPIRED);
      $license->save();
    }
  };
}
