license.license_type.*:
  type: config_entity
  label: 'License type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    status:
      type: int
      label: 'Status'
    expires:
      type: int
      label: 'Expiry'
    expires_automatically:
      type: int
      label: 'Expires automatically'
